import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonSubTypes.Type

@JsonSubTypes(
        value = [
            Type(value = FGItemDescriptor::class, name = "Class'/Script/FactoryGame.FGItemDescriptor'"),
            Type(value = FGBuildableDroneStation::class, name = "Class'/Script/FactoryGame.FGBuildableDroneStation'"),
            Type(value = FGConsumableEquipment::class, name = "Class'/Script/FactoryGame.FGConsumableEquipment'"),
            Type(value = FGSchematic::class, name = "Class'/Script/FactoryGame.FGSchematic'"),
            Type(value = FGConsumableDescriptor::class, name = "Class'/Script/FactoryGame.FGConsumableDescriptor'"),
            Type(value = FGItemDescriptorBiomass::class, name = "Class'/Script/FactoryGame.FGItemDescriptorBiomass'"),
            Type(value = FGResourceDescriptor::class, name = "Class'/Script/FactoryGame.FGResourceDescriptor'"),
            Type(value = FGBuildableWallLightweight::class, name = "Class'/Script/FactoryGame.FGBuildableWallLightweight'"),
            Type(value = FGBuildableWall::class, name = "Class'/Script/FactoryGame.FGBuildableWall'"),
            Type(value = FGBuildableDoor::class, name = "Class'/Script/FactoryGame.FGBuildableDoor'"),
            Type(value = FGRecipe::class, name = "Class'/Script/FactoryGame.FGRecipe'"),
            Type(value = FGCustomizationRecipe::class, name = "Class'/Script/FactoryGame.FGCustomizationRecipe'"),
            Type(value = FGBuildingDescriptor::class, name = "Class'/Script/FactoryGame.FGBuildingDescriptor'"),
            Type(value = FGBuildableCornerWall::class, name = "Class'/Script/FactoryGame.FGBuildableCornerWall'"),
            Type(value = FGBuildableRailroadTrack::class, name = "Class'/Script/FactoryGame.FGBuildableRailroadTrack'"),
            Type(value = FGBuildableBlueprintDesigner::class, name = "Class'/Script/FactoryGame.FGBuildableBlueprintDesigner'"),
            Type(value = FGBuildableFrackingExtractor::class, name = "Class'/Script/FactoryGame.FGBuildableFrackingExtractor'"),
            Type(value = FGBuildableFrackingActivator::class, name = "Class'/Script/FactoryGame.FGBuildableFrackingActivator'"),
            Type(value = FGBuildableGeneratorGeoThermal::class, name = "Class'/Script/FactoryGame.FGBuildableGeneratorGeoThermal'"),
            Type(value = FGBuildableResourceExtractor::class, name = "Class'/Script/FactoryGame.FGBuildableResourceExtractor'"),
            Type(value = FGBuildableSpaceElevator::class, name = "Class'/Script/FactoryGame.FGBuildableSpaceElevator'"),
            Type(value = FGBuildableTradingPost::class, name = "Class'/Script/FactoryGame.FGBuildableTradingPost'"),
            Type(value = FGBuildable::class, name = "Class'/Script/FactoryGame.FGBuildable'"),
            Type(value = FGBuildablePoleLightweight::class, name = "Class'/Script/FactoryGame.FGBuildablePoleLightweight'"),
            Type(value = FGPoleDescriptor::class, name = "Class'/Script/FactoryGame.FGPoleDescriptor'"),
            Type(value = FGBuildableConveyorBelt::class, name = "Class'/Script/FactoryGame.FGBuildableConveyorBelt'"),
            Type(value = FGBuildableWire::class, name = "Class'/Script/FactoryGame.FGBuildableWire'"),
            Type(value = FGBuildablePowerPole::class, name = "Class'/Script/FactoryGame.FGBuildablePowerPole'"),
            Type(value = FGChainsaw::class, name = "Class'/Script/FactoryGame.FGChainsaw'"),
            Type(value = FGEquipmentDescriptor::class, name = "Class'/Script/FactoryGame.FGEquipmentDescriptor'"),
            Type(value = FGItemDescriptorNuclearFuel::class, name = "Class'/Script/FactoryGame.FGItemDescriptorNuclearFuel'"),
            Type(value = FGGolfCartDispenser::class, name = "Class'/Script/FactoryGame.FGGolfCartDispenser'"),
            Type(value = FGSuitBase::class, name = "Class'/Script/FactoryGame.FGSuitBase'"),
            Type(value = FGJetPack::class, name = "Class'/Script/FactoryGame.FGJetPack'"),
            Type(value = FGJumpingStilts::class, name = "Class'/Script/FactoryGame.FGJumpingStilts'"),
            Type(value = FGAmmoTypeProjectile::class, name = "Class'/Script/FactoryGame.FGAmmoTypeProjectile'"),
            Type(value = FGAmmoTypeSpreadshot::class, name = "Class'/Script/FactoryGame.FGAmmoTypeSpreadshot'"),
            Type(value = FGWeapon::class, name = "Class'/Script/FactoryGame.FGWeapon'"),
            Type(value = FGAmmoTypeInstantHit::class, name = "Class'/Script/FactoryGame.FGAmmoTypeInstantHit'"),
            Type(value = FGEquipmentStunSpear::class, name = "Class'/Script/FactoryGame.FGEquipmentStunSpear'"),
            Type(value = FGChargedWeapon::class, name = "Class'/Script/FactoryGame.FGChargedWeapon'"),
            Type(value = FGGasMask::class, name = "Class'/Script/FactoryGame.FGGasMask'"),
            Type(value = FGBuildableWaterPump::class, name = "Class'/Script/FactoryGame.FGBuildableWaterPump'"),
            Type(value = FGBuildableManufacturer::class, name = "Class'/Script/FactoryGame.FGBuildableManufacturer'"),
            Type(value = FGPortableMinerDispenser::class, name = "Class'/Script/FactoryGame.FGPortableMinerDispenser'"),
            Type(value = FGBuildableStorage::class, name = "Class'/Script/FactoryGame.FGBuildableStorage'"),
            Type(value = FGBuildableGeneratorFuel::class, name = "Class'/Script/FactoryGame.FGBuildableGeneratorFuel'"),
            Type(value = FGBuildableMAM::class, name = "Class'/Script/FactoryGame.FGBuildableMAM'"),
            Type(value = FGObjectScanner::class, name = "Class'/Script/FactoryGame.FGObjectScanner'"),
            Type(value = FGBuildableBeamLightweight::class, name = "Class'/Script/FactoryGame.FGBuildableBeamLightweight'"),
            Type(value = FGBuildablePillarLightweight::class, name = "Class'/Script/FactoryGame.FGBuildablePillarLightweight'"),
            Type(value = FGBuildableFactory::class, name = "Class'/Script/FactoryGame.FGBuildableFactory'"),
            Type(value = FGBuildableWalkwayLightweight::class, name = "Class'/Script/FactoryGame.FGBuildableWalkwayLightweight'"),
            Type(value = FGBuildableWalkway::class, name = "Class'/Script/FactoryGame.FGBuildableWalkway'"),
            Type(value = FGBuildablePipelinePump::class, name = "Class'/Script/FactoryGame.FGBuildablePipelinePump'"),
            Type(value = FGBuildablePipelineSupport::class, name = "Class'/Script/FactoryGame.FGBuildablePipelineSupport'"),
            Type(value = FGBuildablePipeline::class, name = "Class'/Script/FactoryGame.FGBuildablePipeline'"),
            Type(value = FGBuildablePipelineJunction::class, name = "Class'/Script/FactoryGame.FGBuildablePipelineJunction'"),
            Type(value = FGBuildablePipeReservoir::class, name = "Class'/Script/FactoryGame.FGBuildablePipeReservoir'"),
            Type(value = FGBuildableResourceSink::class, name = "Class'/Script/FactoryGame.FGBuildableResourceSink'"),
            Type(value = FGBuildableResourceSinkShop::class, name = "Class'/Script/FactoryGame.FGBuildableResourceSinkShop'"),
            Type(value = FGVehicleDescriptor::class, name = "Class'/Script/FactoryGame.FGVehicleDescriptor'"),
            Type(value = FGBuildableManufacturerVariablePower::class, name = "Class'/Script/FactoryGame.FGBuildableManufacturerVariablePower'"),
            Type(value = FGBuildableGeneratorNuclear::class, name = "Class'/Script/FactoryGame.FGBuildableGeneratorNuclear'"),
            Type(value = FGBuildableConveyorLift::class, name = "Class'/Script/FactoryGame.FGBuildableConveyorLift'"),
            Type(value = FGBuildableFoundation::class, name = "Class'/Script/FactoryGame.FGBuildableFoundation'"),
            Type(value = FGBuildableFoundationLightweight::class, name = "Class'/Script/FactoryGame.FGBuildableFoundationLightweight'"),
            Type(value = FGBuildableRamp::class, name = "Class'/Script/FactoryGame.FGBuildableRamp'"),
            Type(value = FGBuildableSplitterSmart::class, name = "Class'/Script/FactoryGame.FGBuildableSplitterSmart'"),
            Type(value = FGBuildableAttachmentMerger::class, name = "Class'/Script/FactoryGame.FGBuildableAttachmentMerger'"),
            Type(value = FGBuildableAttachmentSplitter::class, name = "Class'/Script/FactoryGame.FGBuildableAttachmentSplitter'"),
            Type(value = FGBuildableJumppad::class, name = "Class'/Script/FactoryGame.FGBuildableJumppad'"),
            Type(value = FGConveyorPoleStackable::class, name = "Class'/Script/FactoryGame.FGConveyorPoleStackable'"),
            Type(value = FGBuildableDockingStation::class, name = "Class'/Script/FactoryGame.FGBuildableDockingStation'"),
            Type(value = FGPipeHyperStart::class, name = "Class'/Script/FactoryGame.FGPipeHyperStart'"),
            Type(value = FGBuildablePipeHyper::class, name = "Class'/Script/FactoryGame.FGBuildablePipeHyper'"),
            Type(value = FGBuildablePowerStorage::class, name = "Class'/Script/FactoryGame.FGBuildablePowerStorage'"),
            Type(value = FGBuildableRailroadSignal::class, name = "Class'/Script/FactoryGame.FGBuildableRailroadSignal'"),
            Type(value = FGBuildableTrainPlatformCargo::class, name = "Class'/Script/FactoryGame.FGBuildableTrainPlatformCargo'"),
            Type(value = FGBuildableTrainPlatformEmpty::class, name = "Class'/Script/FactoryGame.FGBuildableTrainPlatformEmpty'"),
            Type(value = FGBuildableRailroadStation::class, name = "Class'/Script/FactoryGame.FGBuildableRailroadStation'"),
            Type(value = FGHoverPack::class, name = "Class'/Script/FactoryGame.FGHoverPack'"),
            Type(value = FGEquipmentZipline::class, name = "Class'/Script/FactoryGame.FGEquipmentZipline'"),
            Type(value = FGBuildableCircuitSwitch::class, name = "Class'/Script/FactoryGame.FGBuildableCircuitSwitch'"),
            Type(value = FGParachute::class, name = "Class'/Script/FactoryGame.FGParachute'"),
            Type(value = FGBuildableRadarTower::class, name = "Class'/Script/FactoryGame.FGBuildableRadarTower'"),
            Type(value = FGBuildableFactorySimpleProducer::class, name = "Class'/Script/FactoryGame.FGBuildableFactorySimpleProducer'"),
            Type(value = FGBuildableSnowDispenser::class, name = "Class'/Script/FactoryGame.FGBuildableSnowDispenser'"),
            Type(value = FGBuildableFactoryBuilding::class, name = "Class'/Script/FactoryGame.FGBuildableFactoryBuilding'"),
            Type(value = FGBuildableWidgetSign::class, name = "Class'/Script/FactoryGame.FGBuildableWidgetSign'"),
            Type(value = FGBuildableLightSource::class, name = "Class'/Script/FactoryGame.FGBuildableLightSource'"),
            Type(value = FGBuildableLadder::class, name = "Class'/Script/FactoryGame.FGBuildableLadder'"),
            Type(value = FGBuildableStair::class, name = "Class'/Script/FactoryGame.FGBuildableStair'"),
            Type(value = FGBuildableFloodlight::class, name = "Class'/Script/FactoryGame.FGBuildableFloodlight'"),
            Type(value = FGBuildableLightsControlPanel::class, name = "Class'/Script/FactoryGame.FGBuildableLightsControlPanel'"),
            Type(value = FGBuildablePassthrough::class, name = "Class'/Script/FactoryGame.FGBuildablePassthrough'"),
        ]
)

open class GameEntity {
}
