spring:
  neo4j:
    driver: org.neo4j.ogm.drivers.embedded.driver.EmbeddedDriver
    uri: bolt://${NEO4J_HOST}:${NEO4J_PORT}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
logging:
  level:
    web: DEBUG
    org:
      springframework:
        data:
          neo4j:
            cypher: DEBUG
springdoc:
  api-docs:
    path: /openapi/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
factoryplanner:
  filestorage:
    url: ${FILE_STORAGE_URL}
    assets:
      accessKey: ${FILE_STORAGE_ASSETS_ACCESS_KEY}
      secretKey: ${FILE_STORAGE_ASSETS_SECRET_KEY}
    resources:
      accessKey: ${FILE_STORAGE_RESOURCES_ACCESS_KEY}
      secretKey: ${FILE_STORAGE_RESOURCES_SECRET_KEY}
